a =input('Qualquer coisa= ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaço? ', a.isspace())
print('É um número? ',a.isnumeric())
print('É alfabetico',a.isalpha())
print('Tem números e letras? ',a.isalnum())
print('Está em maiusculo? ',a.isupper())
print('Está em minusculo? ',a.islower())
print('Esta captalizada? ',a.capitalize())