brasileirão = ('América Fc Saf - MG', 'Athletico Paranaense - PR', 'Atlético - GO', 'Atlético Mineiro - MG', 'Avaí - SC', 'Botafogo - RJ', 'Ceará - CE', 'Corinthians - SP', 'Coritiba - PR', 'Cuiabá Saf - MT', 'Flamengo - RJ', 'Fluminense - RJ', 'Fortaleza - CE', 'Goiás - GO', 'Internacional - RS', 'Juventude - RS', 'Palmeiras - SP', 'Red Bull Bragantino - SP', 'Santos - SP', 'São Paulo - SP')
print(f'Lista de times do brasileirão: {brasileirão}')
print('=-='*15)
print(f'Os 5 primeiros colocados: {brasileirão[0:5]}')
print('=-='*15)
print(f'Os 4 ultimos colocados: {brasileirão[-4:]}')
print('=-='*15)
print(f'Nome dos times em ordem alfabética: {sorted(brasileirão)}')
print('=-='*15)
print(f'O 8 colocado é o time {brasileirão[7]}')